language: python
dist: trusty
os:
- linux
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script: "make CC=clang TF_INCLUDE=~/virtualenv/python3.5/lib/python3.5/site-packages/tensorflow/include"
# command to run tests
script: "python test.py"
